# Generated by Django 4.1.5 on 2023-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Views', models.IntegerField(default=0, null=True)),
                ('Likes', models.IntegerField(default=0, null=True)),
                ('Average', models.IntegerField(default=0, null=True)),
                ('Dislikes', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
