# Generated by Django 4.1.5 on 2023-01-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='slug',
        ),
    ]
